version: '2'
services:
    db:
        build: ./mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./mysql/data:/var/lib/mysql
    web:
        build: ./web
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./src:/var/www/html
            - ./web/conf:/etc/apache2/sites-enabled
        links:
            - db