version: '2'
services:
    db:
        image: mysql:5.6
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./mysql:/var/lib/mysql

    php:
        build: ./php-fpm
        expose:
            - "9000"
        volumes:
            - ./src:/var/www
        links:
            - db